### ISSUE TITLE
Pair-programming Issue - Morning Session Group

### ISSUE THREAD

**Issue by VitorGuedesMadeira** [Nyame-Wolf/To-Do-list#2]
### To-do List project (Microverse)
- [ ] Kindly check the remove btn
- [ ] Kindly follow the template for the styling
- [ ] Fix Linters for javascript

**Comment by nimplay** [comment]
Kindly I recomend use Artificial Inteligence in a part of your project.
